### ISSUE TITLE
Could use an explanation of Import-ProfileConfig

### ISSUE THREAD

**Issue by lboening** [claudiospizzi/ProfileFever#1]
I am using your module and could use an example for Import-ProfileConfig. Here's a feature request: create a function called New-ProfileConfig.

**Comment by claudiospizzi** [comment]
@lboening I've used that in the past to host my profile. But I don't do that anymore and now I have a different solution. The modules aims more in access remote system. I guess thinking about that, I should rename the module as the name and the features do not match anymore since v5.
