### ISSUE TITLE
[Bug]: What happened to Performance functions?

### ISSUE THREAD

**Issue by greatquux** [claudiospizzi/ProfileFever#2]
### What happened?

The performance functions like Measure-Storage seem to have disappeared

### Errors / Logs

I installed this module via Import-Module but can't find the Measure-* functions and though they are mentioned in the repository the code is not here.

### PowerShell Version

5.1

### Module Version

5.1

**Comment by claudiospizzi** [comment]
Hi @greatquux 

Actually, they were removed with v5 and replaced with the Show-LauncherPSRemotingWelcome which shows the core performance data when entring a remote session.

I wasn't aware of anyone using this as almost no feedback reached out to me. What was your use case with the measure functions, using them locally or in a remote session? I am considering bringing them back in a v5.2.

Bests
Claudio

**Comment by greatquux** [comment]
Maybe everyone who downloaded it liked it without giving feedback? 🤷  But it looked pretty cool to me! We do have monitoring software but sometimes you just want to run a quick command (with a background shell) to see things like disk queue and average response time without logging in and opening up task manager.  That's how I was using Measure-Storage ;  as well know programmers have just started eating up I/O bandwidth like no tomorrow and these things have to be monitored.

**Comment by claudiospizzi** [comment]
Thanks for your feedback. I've pushed a release bringing back the measure functions:

[https://www.powershellgallery.com/packages/ProfileFever/5.2.0](https://www.powershellgallery.com/packages/ProfileFever/5.2.0)

Maybe you can give it a try.

**Comment by greatquux** [comment]
It works great!! Thanks so much, it's definitely helpful, not to get meta or anything too much but everything you put into the world has an effect, and this is a good one.

**Comment by claudiospizzi** [comment]
Thanks for the feedback, makes me glad to see that you and others are using my modules as well and find it useful.
